const mockDB = {
  restaurants: [
    {
      id: 1,
      image: "",
      name: "Coral Reef Catch",
      cuisine: "Local Seafood",
      hours: "11am - 9pm",
      location: "Harbor District",
      description: "Family-owned restaurant serving the freshest daily catch with traditional Taniti rice preparations. Known for their coconut-crusted mahi-mahi.",
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.6,
      priceRange: "$$"
    },
    {
      id: 2,
      image: "",
      name: "Island Fisherman's Table",
      cuisine: "Local Seafood",
      hours: "5pm - 10pm",
      location: "Beachfront",
      description: "Upscale dining featuring locally-sourced fish with aromatic island rice dishes. Spectacular sunset views from every table.",
      hasKidsMenu: false,
      isLocalFavorite: false,
      rating: 4.8,
      priceRange: "$$$"
    },
    {
      id: 3,
      image: "",
      name: "Taniti Bay Grill",
      cuisine: "Local Seafood",
      hours: "12pm - 8pm",
      location: "Main Street",
      description: "Casual spot beloved by locals for generous portions of grilled fish and perfectly seasoned rice bowls. Don't miss the fish tacos!",
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.4,
      priceRange: "$"
    },
    {
      id: 4,
      image: "",
      name: "Ocean's Bounty",
      cuisine: "Local Seafood",
      hours: "10am - 9pm",
      location: "Fishing Village",
      description: "Traditional fishing village eatery where recipes have been passed down for generations. Famous for their whole roasted fish and coconut rice.",
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.3,
      priceRange: "$"
    },
    {
      id: 5,
      image: "",
      name: "Blue Lagoon Seafood",
      cuisine: "Local Seafood",
      hours: "4pm - 10pm",
      location: "Resort Area",
      description: "Modern take on traditional Taniti seafood with creative rice preparations. Popular with both tourists and locals for their innovative dishes.",
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 4.2,
      priceRange: "$$"
    },
    {
      id: 6,
      image: "",
      name: "Taniti Burger Co.",
      cuisine: "American",
      hours: "11am - 11pm",
      location: "Downtown",
      description: "Classic American burgers, fries, and shakes with a tropical twist. Their pineapple burger is a must-try for visitors.",
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 4.1,
      priceRange: "$$"
    },
    {
      id: 7,
      image: "",
      name: "Paradise Diner",
      cuisine: "American",
      hours: "6am - 10pm",
      location: "Main Street",
      description: "All-day American comfort food from pancakes to steaks. A reliable spot for familiar flavors with friendly service and generous portions.",
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 3.9,
      priceRange: "$$"
    },
    {
      id: 8,
      image: "",
      name: "Sunset Sports Bar & Grill",
      cuisine: "American",
      hours: "12pm - 12am",
      location: "Beach Road",
      description: "Sports bar atmosphere with American favorites like wings, nachos, and BBQ. Multiple screens for watching games while enjoying island breezes.",
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 4.0,
      priceRange: "$$"
    },
    {
      id: 9,
      image: "",
      name: "Bamboo Garden",
      cuisine: "Pan-Asian",
      hours: "5pm - 10pm",
      location: "Resort Area",
      description: "Elegant Pan-Asian fusion featuring dishes from Thailand, Japan, and Vietnam. Beautiful bamboo garden setting with koi ponds.",
      hasKidsMenu: false,
      isLocalFavorite: false,
      rating: 4.7,
      priceRange: "$$$"
    },
    {
      id: 10,
      image: "",
      name: "Spice Route",
      cuisine: "Pan-Asian",
      hours: "11:30am - 9:30pm",
      location: "Shopping District",
      description: "Casual Pan-Asian eatery with bold flavors from across Asia. Known for their curry dishes and fresh spring rolls.",
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.5,
      priceRange: "$$"
    },
    {
      id: 11,
      image: "",
      name: "Taniti Microbrewery",
      cuisine: "Local Seafood",
      hours: "3pm - 12am",
      location: "Harbor District",
      description: "Local microbrewery crafting unique beers with tropical ingredients. Try their coconut porter and mango wheat ale.",
      hasKidsMenu: false,
      isLocalFavorite: true,
      rating: 4.4,
      priceRange: "$$"
    },
    {
      id: 12,
      image: "",
      name: "The Anchor Pub",
      cuisine: "American",
      hours: "4pm - 1am",
      location: "Downtown",
      description: "Classic pub atmosphere with local and imported beers. Popular gathering spot for both locals and visitors.",
      hasKidsMenu: false,
      isLocalFavorite: true,
      rating: 4.2,
      priceRange: "$"
    },
    {
      id: 13,
      image: "",
      name: "Tiki Torch Tavern",
      cuisine: "Local Seafood",
      hours: "5pm - 2am",
      location: "Beachfront",
      description: "Tropical tiki bar with creative cocktails and a selection of craft beers. Live music on weekends.",
      hasKidsMenu: false,
      isLocalFavorite: false,
      rating: 4.3,
      priceRange: "$$"
    }
  ],
  hotels: [
    {
      id: 1,
      image: "",
      name: "Taniti Grand Resort & Spa",
      type: "Resort",
      stars: 4,
      priceRange: "$$$$",
      location: "Beachfront - North Shore",
      description: "Taniti's premier luxury resort featuring world-class amenities, multiple dining options, and pristine beachfront access. Perfect for those seeking the ultimate island getaway.",
      amenities: [
        "Private Beach Access",
        "Full-Service Spa",
        "Multiple Swimming Pools",
        "Fitness Center",
        "Tennis Court",
        "Golf Course Access",
        "Kids Club",
        "Concierge Service",
        "Room Service 24/7",
        "Free WiFi",
        "Airport Shuttle",
        "Multiple Restaurants",
        "Poolside Bar",
        "Active Equipment",
        "Laundry Service",
        "Business Center"
      ],
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 4.6,
      roomCount: 180
    },
    {
      id: 2,
      image: "",
      name: "Island Backpackers Hostel",
      type: "Hostel",
      stars: 2,
      priceRange: "$",
      location: "Downtown",
      description: "Budget-friendly hostel perfect for adventurous travelers. Clean, safe, and social atmosphere with easy access to local attractions and nightlife.",
      amenities: [
        "Shared Kitchen",
        "Common Lounge Area",
        "Free WiFi",
        "Luggage Storage",
        "Laundry Facilities",
        "Bike Rentals",
        "Tour Booking Service",
        "Shared Bathrooms",
        "Lockers",
        "Outdoor Terrace"
      ],
      hasKidsMenu: false,
      isLocalFavorite: true,
      rating: 4.1,
      roomCount: 24
    },
    {
      id: 3,
      image: "",
      name: "Coral Bay Hotel",
      type: "Hotel",
      stars: 3,
      priceRange: "$$",
      location: "Harbor District",
      description: "Family-owned boutique hotel with personalized service and stunning harbor views. Three generations of hospitality excellence.",
      amenities: [
        "Harbor Views",
        "Free WiFi",
        "Continental Breakfast",
        "Swimming Pool",
        "Restaurant",
        "Bar/Lounge",
        "Concierge Service",
        "Laundry Service",
        "Parking",
        "Air Conditioning",
        "Balconies"
      ],
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.4,
      roomCount: 32
    },
    {
      id: 4,
      image: "",
      name: "Sunset Palm Hotel",
      type: "Hotel",
      stars: 3,
      priceRange: "$$",
      location: "West Beach",
      description: "Charming family-run hotel known for spectacular sunset views and warm island hospitality. Each room uniquely decorated with local art.",
      amenities: [
        "Sunset Views",
        "Free WiFi",
        "Swimming Pool",
        "Beach Access",
        "Restaurant",
        "Complimentary Breakfast",
        "Garden Terrace",
        "Parking",
        "Air Conditioning",
        "Mini Fridge",
        "Coffee Maker"
      ],
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.3,
      roomCount: 28
    },
    {
      id: 5,
      image: "",
      name: "Tropical Breeze Inn",
      type: "Hotel",
      stars: 2,
      priceRange: "$",
      location: "Village Center",
      description: "Cozy family-owned inn offering comfortable accommodations at great value. Walking distance to local shops and restaurants.",
      amenities: [
        "Free WiFi",
        "Continental Breakfast",
        "Swimming Pool",
        "Garden Views",
        "Parking",
        "Air Conditioning",
        "Mini Fridge",
        "Coffee Maker",
        "Laundry Service"
      ],
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.0,
      roomCount: 18
    },
    {
      id: 6,
      image: "",
      name: "Mango Tree Hotel",
      type: "Hotel",
      stars: 3,
      priceRange: "$$",
      location: "Hillside",
      description: "Elevated hotel with panoramic island views, surrounded by lush tropical gardens. Family-owned for over 20 years.",
      amenities: [
        "Mountain Views",
        "Ocean Views",
        "Free WiFi",
        "Swimming Pool",
        "Restaurant",
        "Tropical Gardens",
        "Hiking Trail Access",
        "Complimentary Breakfast",
        "Parking",
        "Air Conditioning",
        "Balconies"
      ],
      hasKidsMenu: true,
      isLocalFavorite: false,
      rating: 4.2,
      roomCount: 25
    },
    {
      id: 7,
      image: "",
      name: "Seashell Bed & Breakfast",
      type: "Bed & Breakfast",
      stars: 3,
      priceRange: "$$",
      location: "Coastal Road",
      description: "Intimate B&B with just six rooms, each with ocean views. Hosts Maria and Carlos serve homemade breakfast featuring local ingredients.",
      amenities: [
        "Ocean Views",
        "Homemade Breakfast",
        "Free WiFi",
        "Garden Patio",
        "Beach Access",
        "Parking",
        "Air Conditioning",
        "Mini Fridge",
        "Private Bathrooms",
        "Personalized Service"
      ],
      hasKidsMenu: false,
      isLocalFavorite: true,
      rating: 4.7,
      roomCount: 6
    },
    {
      id: 8,
      image: "",
      name: "Hibiscus House B&B",
      type: "Bed & Breakfast",
      stars: 3,
      priceRange: "$$",
      location: "Historic District",
      description: "Beautifully restored colonial home turned B&B. Each room tells a story of Taniti's rich history with modern comfort.",
      amenities: [
        "Historic Architecture",
        "Gourmet Breakfast",
        "Free WiFi",
        "Library/Reading Room",
        "Garden Courtyard",
        "Parking",
        "Air Conditioning",
        "Antique Furnishings",
        "Private Bathrooms",
        "Cultural Tours"
      ],
      hasKidsMenu: false,
      isLocalFavorite: false,
      rating: 4.5,
      roomCount: 8
    },
    {
      id: 9,
      image: "",
      name: "Palm Grove Retreat",
      type: "Bed & Breakfast",
      stars: 3,
      priceRange: "$$$",
      location: "Secluded Bay",
      description: "Adults-only B&B nestled in a private palm grove. Perfect for romantic getaways with luxury amenities and personalized attention.",
      amenities: [
        "Adults Only",
        "Private Beach",
        "Gourmet Breakfast",
        "Free WiFi",
        "Spa Services",
        "Kayak Rentals",
        "Wine Cellar",
        "Sunset Deck",
        "Air Conditioning",
        "Luxury Linens",
        "Concierge Service"
      ],
      hasKidsMenu: false,
      isLocalFavorite: false,
      rating: 4.8,
      roomCount: 5
    },
    {
      id: 10,
      image: "",
      name: "Garden View B&B",
      type: "Bed & Breakfast",
      stars: 2,
      priceRange: "$",
      location: "Inland Valley",
      description: "Budget-friendly B&B surrounded by tropical gardens and fruit trees. Hosts offer cooking classes and garden tours.",
      amenities: [
        "Tropical Gardens",
        "Homemade Breakfast",
        "Free WiFi",
        "Cooking Classes",
        "Garden Tours",
        "Parking",
        "Fan Cooling",
        "Shared Bathrooms",
        "Fruit Picking",
        "Hammock Area"
      ],
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.1,
      roomCount: 7
    },
    {
      id: 11,
      image: "",
      name: "Coconut Cove Inn",
      type: "Bed & Breakfast",
      stars: 3,
      priceRange: "$$",
      location: "South Shore",
      description: "Charming beachside B&B with direct access to a quiet cove. Known for their fresh coconut pancakes and snorkeling equipment loans.",
      amenities: [
        "Private Cove Access",
        "Fresh Coconut Breakfast",
        "Free WiFi",
        "Snorkeling Equipment",
        "Beach Chairs",
        "Parking",
        "Air Conditioning",
        "Mini Fridge",
        "Private Bathrooms",
        "Hammocks"
      ],
      hasKidsMenu: true,
      isLocalFavorite: true,
      rating: 4.4,
      roomCount: 9
    }
  ],
  activities: [
    {
      id: 1,
      image: "",
      name: "Yellow Leaf Bay Beach",
      categories: ["Beach", "Leisure"],
      location: "Taniti City",
      duration: "All Day",
      price: 0,
      description: "Pristine white sandy beaches encircling Yellow Leaf Bay. Perfect for swimming, sunbathing, and beach games with crystal clear waters.",
      tags: ["Free", "Family-Friendly", "Kid-Friendly", "Beach", "Swimming", "Popular"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.8
    },
    {
      id: 2,
      image: "",
      name: "Snorkeling Adventure",
      categories: ["Active", "Water", "Nature"],
      location: "Various Beach Locations",
      duration: "3 hours",
      price: 45,
      description: "Explore Taniti's vibrant coral reefs and tropical marine life. Equipment and instruction included for all skill levels.",
      tags: ["Active", "Family-Friendly", "Kid-Friendly", "Marine Life", "Adventure", "Popular"],
      difficulty: "Easy",
      ageRestriction: "6+",
      rating: 4.6
    },
    {
      id: 3,
      image: "",
      name: "Chartered Fishing Tours",
      categories: ["Active", "Water"],
      location: "Harbor District",
      duration: "4-8 hours",
      price: 120,
      description: "Deep sea fishing adventures with experienced local captains. All equipment provided, catch cleaning included.",
      tags: ["Active", "Adventure", "Half Day", "Full Day", "Fishing"],
      difficulty: "Easy",
      ageRestriction: "8+",
      rating: 4.5
    },
    {
      id: 4,
      image: "",
      name: "Rainforest Hiking Trails",
      categories: ["Nature", "Hiking", "Active"],
      location: "Taniti Rainforest",
      duration: "2-6 hours",
      price: 25,
      description: "Guided hikes through lush tropical rainforest with waterfalls, exotic birds, and native plants. Multiple trail difficulty options.",
      tags: ["Nature", "Hiking", "Adventure", "Family-Friendly", "Wildlife", "Popular"],
      difficulty: "Varies",
      ageRestriction: "5+",
      rating: 4.7
    },
    {
      id: 5,
      image: "",
      name: "Rainforest Zip-lining",
      categories: ["Active", "Ziplining", "Nature"],
      location: "Taniti Rainforest",
      duration: "3 hours",
      price: 85,
      description: "Soar through the rainforest canopy on our thrilling zip-line course. Seven lines with breathtaking views and wildlife spotting.",
      tags: ["Adventure", "Adrenaline", "Nature", "Canopy", "Thrilling"],
      difficulty: "Moderate",
      ageRestriction: "12+",
      rating: 4.8
    },
    {
      id: 6,
      image: "",
      name: "Active Volcano Tour",
      categories: ["Nature", "Hiking", "Scenic"],
      location: "Mount Taniti",
      duration: "6 hours",
      price: 95,
      description: "Guided tour to Taniti's active volcano with geological insights, lava viewing (when safe), and spectacular crater views.",
      tags: ["Nature", "Adventure", "Volcano", "Geology", "Popular", "Full Day"],
      difficulty: "Moderate",
      ageRestriction: "10+",
      rating: 4.9
    },
    {
      id: 7,
      image: "",
      name: "Helicopter Volcano Tour",
      categories: ["Scenic", "Active"],
      location: "Taniti Airport",
      duration: "1 hour",
      price: 250,
      description: "Aerial tour of the island including close-up volcano views, rainforest canopy, and coastal panoramas. Unforgettable experience!",
      tags: ["Adventure", "Aerial", "Volcano", "Luxury", "Scenic", "Adrenaline"],
      difficulty: "Easy",
      ageRestriction: "3+",
      rating: 4.9
    },
    {
      id: 8,
      image: "",
      name: "Taniti History Museum",
      categories: ["Cultural", "Historical"],
      location: "Taniti City",
      duration: "2 hours",
      price: 15,
      description: "Discover Taniti's rich cultural heritage, from ancient civilizations to modern development. Interactive exhibits and artifacts.",
      tags: ["Cultural", "Educational", "Family-Friendly", "Kid-Friendly", "History", "Indoor"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.2
    },
    {
      id: 9,
      image: "",
      name: "Island Art Galleries Tour",
      categories: ["Cultural"],
      location: "Various Locations",
      duration: "3 hours",
      price: 30,
      description: "Visit multiple local art galleries featuring works by Tanitian artists. Includes traditional crafts and contemporary pieces.",
      tags: ["Cultural", "Art", "Educational", "Local Artists", "Indoor"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.1
    },
    {
      id: 10,
      image: "",
      name: "Island Bus Tour",
      categories: ["Scenic", "Cultural"],
      location: "Taniti City (Departure)",
      duration: "4 hours",
      price: 40,
      description: "Comprehensive island tour visiting key landmarks, scenic viewpoints, and cultural sites with knowledgeable local guides.",
      tags: ["Sightseeing", "Family-Friendly", "Kid-Friendly", "Educational", "Popular", "Relaxing"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.4
    },
    {
      id: 11,
      image: "",
      name: "Island Boat Tour",
      categories: ["Active", "Scenic", "Water"],
      location: "Harbor District",
      duration: "3 hours",
      price: 55,
      description: "Coastal boat tour showcasing hidden coves, sea caves, and marine wildlife. Includes swimming stops and refreshments.",
      tags: ["Active", "Sightseeing", "Family-Friendly", "Marine Life", "Relaxing"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.5
    },
    {
      id: 12,
      image: "",
      name: "Pulse Dance Club",
      categories: ["Entertainment"],
      location: "Merriton Landing",
      duration: "Evening",
      price: 20,
      description: "Taniti's hottest new dance club featuring international DJs, craft cocktails, and a state-of-the-art sound system.",
      tags: ["Nightlife", "Dancing", "Adults Only", "Music", "Cocktails"],
      difficulty: "Easy",
      ageRestriction: "21+",
      rating: 4.3
    },
    {
      id: 13,
      image: "",
      name: "Island Cinema",
      categories: ["Entertainment", "Leisure"],
      location: "Merriton Landing",
      duration: "2 hours",
      price: 12,
      description: "Modern movie theater showing latest releases and classic films. Comfortable seating with local snacks available.",
      tags: ["Entertainment", "Family-Friendly", "Kid-Friendly", "Indoor", "Movies", "Relaxing"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.0
    },
    {
      id: 14,
      image: "",
      name: "Tropical Arcade",
      categories: ["Entertainment", "Leisure"],
      location: "Merriton Landing",
      duration: "1-3 hours",
      price: 25,
      description: "Classic and modern arcade games in a tropical-themed setting. Great for families and competitive gamers alike.",
      tags: ["Entertainment", "Family-Friendly", "Kid-Friendly", "Indoor", "Games", "Fun"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.2
    },
    {
      id: 15,
      image: "",
      name: "Strike Zone Bowling",
      categories: ["Entertainment", "Leisure"],
      location: "Merriton Landing",
      duration: "2 hours",
      price: 18,
      description: "Modern bowling alley with 12 lanes, cosmic bowling nights, and a full snack bar. Perfect for groups and families.",
      tags: ["Entertainment", "Family-Friendly", "Kid-Friendly", "Indoor", "Sports", "Groups"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.1
    },
    {
      id: 16,
      image: "",
      name: "Taniti Links Golf Course",
      categories: ["Active", "Leisure"],
      location: "North Shore",
      duration: "4 hours",
      price: 75,
      description: "Nine-hole championship golf course with ocean views and challenging tropical hazards. Opening next year!",
      tags: ["Sports", "Golf", "Scenic", "Coming Soon", "Ocean Views"],
      difficulty: "Moderate",
      ageRestriction: "All Ages",
      rating: 0,
      status: "Opening 2026"
    },
    {
      id: 17,
      image: "",
      name: "Sunset Catamaran Cruise",
      categories: ["Active", "Water", "Scenic"],
      location: "Harbor District",
      duration: "3 hours",
      price: 65,
      description: "Romantic sunset cruise with complimentary drinks, light appetizers, and stunning views of Taniti's coastline.",
      tags: ["Active", "Romantic", "Sunset", "Relaxing", "Drinks", "Scenic"],
      difficulty: "Easy",
      ageRestriction: "All Ages",
      rating: 4.7
    },
    {
      id: 18,
      image: "",
      name: "Traditional Cooking Class",
      categories: ["Cultural"],
      location: "Village Center",
      duration: "4 hours",
      price: 80,
      description: "Learn to prepare authentic Tanitian dishes using local ingredients. Includes market visit, cooking, and dining experience.",
      tags: ["Cultural", "Educational", "Food", "Hands-on", "Local Experience"],
      difficulty: "Easy",
      ageRestriction: "8+",
      rating: 4.6
    },
    {
      id: 19,
      image: "",
      name: "Sea Turtle Watching",
      categories: ["Nature", "Beach"],
      location: "Protected Beach Areas",
      duration: "2 hours",
      price: 35,
      description: "Guided evening tours to observe nesting sea turtles (seasonal). Educational and conservation-focused experience.",
      tags: ["Nature", "Wildlife", "Educational", "Conservation", "Evening", "Seasonal"],
      difficulty: "Easy",
      ageRestriction: "6+",
      rating: 4.8
    },
    {
      id: 20,
      image: "",
      name: "Kayak Mangrove Tour",
      categories: ["Active", "Water", "Nature"],
      location: "East Coast Mangroves",
      duration: "3 hours",
      price: 50,
      description: "Paddle through pristine mangrove channels spotting birds, fish, and learning about this unique ecosystem.",
      tags: ["Active", "Nature", "Wildlife", "Educational", "Peaceful", "Eco-Tour"],
      difficulty: "Easy",
      ageRestriction: "8+",
      rating: 4.5
    }
  ]
};

window.mockDB = mockDB;